Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
Not Found: /logib
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\buy_ticket_form.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
Visit index page
Not Found: /admin
Not Found: /admin
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\buy_ticket_form.py changed, reloading.
Watching for file changes with StatReloader
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 252, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 290, in build_widget_attrs
    if not widget.is_hidden and self.errors:
                                ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 74, in errors
    return self.form.errors.get(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 290, in build_widget_attrs
    if not widget.is_hidden and self.errors:
                                ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 74, in errors
    return self.form.errors.get(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 290, in build_widget_attrs
    if not widget.is_hidden and self.errors:
                                ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 74, in errors
    return self.form.errors.get(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 252, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 252, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\buy_ticket_form.py changed, reloading.
Watching for file changes with StatReloader
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 252, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 252, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 252, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 171, in buy_ticket
    return render(request, 'client/buy_ticket.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 252, in non_field_errors
    return self.errors.get(
           ^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\forms\forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CharField' object has no attribute 'value_from_datadict'
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\buy_ticket_form.py changed, reloading.
Watching for file changes with StatReloader
Buy ticket
Buy ticket
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\buy_ticket_form.py changed, reloading.
Watching for file changes with StatReloader
Buy ticket
Buy ticket
Buy ticket
Buy ticket
Buy ticket
Visit promo page
Buy ticket
Visit my tickets page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit my tickets page
Visit my tickets page
Buy ticket
Buy ticket
Visit my tickets page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\models\Place.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /animals
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\animal_filter.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 231, in animal_list
    animals = animals.filter(counties__in=form.cleaned_data['place']).distinct()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1532, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1346, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1323, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "Jungle Enclosure": Must be "Country" instance.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 231, in animal_list
    animals = animals.filter(place__animal__in=form.cleaned_data['place']).distinct()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1376, in build_lookup
    lhs = self.try_transform(lhs, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'animal' for ForeignKey or join on the field not permitted.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 231, in animal_list
    animals = animals.filter(place__animal=form.cleaned_data['place']).distinct()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1383, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1427, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'animal' for ForeignKey or join on the field not permitted.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 231, in animal_list
    animals = animals.filter(animal__place=form.cleaned_data['place']).distinct()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'animal' into field. Choices are: birthday, counties, created_at, employee, employee_id, facts, food, id, name, parameters, parameters_id, photo, place, place_id, receipt_date, updated_at, view, view_id
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit my tickets page
Logout
Visit index page
Not Found: /all_animals
Not Found: /admin/all_animals/
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
Visit my animals page
Internal Server Error: /super/all_animals/
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 190, in my_animals
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
Visit animal details page
Internal Server Error: /my_animals/1
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 203, in animal_detail
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
Visit animal details page
Internal Server Error: /my_animals/1
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 203, in animal_detail
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit animal details page
Visit animal details page
Visit animal details page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
Visit animal details page
Visit animal details page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
Visit animal details page
Not Found: /my_animals/3
Visit animal details page
Visit animal details page
Internal Server Error: /animals/4
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view zoo.views.animal_detail didn't return an HttpResponse object. It returned None instead.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit animal details page
Visit my animals page
Internal Server Error: /my_animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 190, in my_animals
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
Visit my animals page
Internal Server Error: /my_animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 190, in my_animals
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit my animals page
Internal Server Error: /my_animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 190, in my_animals
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit my animals page
Internal Server Error: /my_animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 190, in my_animals
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit my animals page
Internal Server Error: /my_animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 190, in my_animals
    employee = request.user.employee
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee.RelatedObjectDoesNotExist: User has no employee.
Visit animal details page
Internal Server Error: /super/all_animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 257, in super_user_animal_list
    if form.cleaned_data['view']:
       ~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'view'
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/all_animals
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 263, in super_user_animal_list
    animals = animals.filter(food__food_name=form.cleaned_data['food']).distinct()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1559, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1389, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 158, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\lookups.py", line 360, in get_prep_lookup
    raise ValueError(
ValueError: The QuerySet value for an exact lookup must be limited to one result using slicing.
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /all_animals
Not Found: /_animals
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\animal_filter.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\animal_filter.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Logout
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\animal_filter.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /admin
Visit index page
Logout
Visit index page
Visit index page
Visit promo page
Buy ticket
Buy ticket
Visit my tickets page
Logout
Visit index page
Visit my animals page
Visit animal details page
Visit animal details page
Visit animal details page
Logout
Visit index page
Visit animal details page
Visit animal details page
Visit animal details page
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 323, in super_user_employee
    places = Place.objects.filter(animal__employee=employee).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'animal' into field. Choices are: animals, created_at, employees, has_heating, has_swimming, id, name, number, quarter, quarter_id, square, updated_at
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 323, in super_user_employee
    places = Place.objects.filter(animal__employee_id=employee.id).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'animal' into field. Choices are: animals, created_at, employees, has_heating, has_swimming, id, name, number, quarter, quarter_id, square, updated_at
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 326, in super_user_employee
    for j in i.animal_set:
TypeError: 'RelatedManager' object is not iterable
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 326, in super_user_employee
    for j in i.animals:
TypeError: 'RelatedManager' object is not iterable
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 326, in super_user_employee
    for j in i.animals:
             ^^^^^^^^^
AttributeError: 'Place' object has no attribute 'animals'. Did you mean: 'animal_set'?
C:\Users\sasha\PycharmProjects\Lab_5\zoo\models\Animal.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 326, in super_user_employee
    for j in i.animals:
TypeError: 'RelatedManager' object is not iterable
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 326, in super_user_employee
    for j in i.animals.all():
TypeError: 'RelatedManager' object is not iterable
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 328, in super_user_employee
    filtered += i
TypeError: 'Place' object is not iterable
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 328, in super_user_employee
    filtered += i
TypeError: 'Place' object is not iterable
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 328, in super_user_employee
    filtered += i
TypeError: 'Place' object is not iterable
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 328, in super_user_employee
    filtered += i
TypeError: unsupported operand type(s) for +=: 'QuerySet' and 'Place'
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 328, in super_user_employee
    filtered += i
TypeError: unsupported operand type(s) for +=: 'QuerySet' and 'Place'
Internal Server Error: /super/employees/2
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 328, in super_user_employee
    filtered.append(i)
    ^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +=: 'QuerySet' and 'Place'
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Visit index page
Logout
Visit index page
Visit $1 new page
Visit news page
Visit index page
Visit about page
Visit news page
Visit terms page
Visit news page
Visit terms page
Visit vacancy page
Visit policy page
Visit review page
Create comment
Create comment
Visit review page
Visit promo page
Visit promo page
Buy ticket
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\buy_ticket_form.py changed, reloading.
Watching for file changes with StatReloader
Buy ticket
C:\Users\sasha\PycharmProjects\Lab_5\zoo\forms\buy_ticket_form.py changed, reloading.
Watching for file changes with StatReloader
Buy ticket
Buy ticket
Buy ticket
Internal Server Error: /buy_ticket
Traceback (most recent call last):
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py", line 172, in buy_ticket
    total_price *= (1 - obj.discount / 100)
                        ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'discount'
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\sasha\PycharmProjects\Lab_5\zoo\views.py changed, reloading.
Watching for file changes with StatReloader
Buy ticket
Visit my tickets page
Buy ticket
Visit my tickets page
Logout
Visit index page
Visit my animals page
Visit animal details page
Visit animal details page
Visit animal details page
Visit animal details page
Logout
Visit index page
Visit animal details page
Visit animal details page
